apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: jsbdevdocker/calculator_microservice:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
        # Read in the secret for the MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_URI
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 3000       # Port exposed by the service
      targetPort: 3000 # Port inside the container
  type: LoadBalancer # GKE will provision the public IP this way