apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec: 
      restartPolicy: OnFailure
      containers:
      - name: mongo-setup
        image: mongo:6.0
        command: ["sh", "-c"]
        args:
        - |
          mongo admin --host mongodb --eval "
            db = db.getSiblingDB('$MONGO_DATABASE');
            db.createUser({
              user: '$MONGODB_USERNAME',
              pwd: '$MONGO_PASSWORD',
              roles: [
                { role: 'readWrite', db: '$MONGO_DATABASE' }
              ]
            });
          "
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_DATABASE
